# -*- coding: utf-8 -*-
"""publicSapient.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFKTfRPERSEugafelSY93_X1CE1IuEx6
"""

import os

# Specify the path to your images folder in Google Drive
image_folder_path = '/content/drive/MyDrive/images'

# List the contents of the folder
try:
    files_in_folder = os.listdir(image_folder_path)
    print(f"Files in {image_folder_path}:")
    for item in files_in_folder:
        print(item)
except FileNotFoundError:
    print(f"Error: The folder '{image_folder_path}' was not found. Please ensure the path is correct and your Drive is mounted.")
except Exception as e:
    print(f"An error occurred: {e}")

import os
import numpy as np
import faiss
from PIL import Image
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("clip-ViT-B-32")
print("Model Loaded Successfully")

from google.colab import drive
drive.mount('/content/drive')

import requests

os.makedirs("images", exist_ok=True)

urls = [
    "https://images.unsplash.com/photo-1518717758536-85ae29035b6d",  # dog
    "https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d",  # cat
    "https://images.unsplash.com/photo-1507149833265-60c372daea22",  # puppy
    "https://images.unsplash.com/photo-1492724441997-5dc865305da7",  # nature
    "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee"   # mountain
]

image_paths = []

for i, url in enumerate(urls):
    response = requests.get(url)
    path = f"images/img_{i}.jpg"

    with open(path, "wb") as f:
        f.write(response.content)

    image_paths.append(path)

print("Downloaded Images:", len(image_paths))

embeddings = []

for path in image_paths:
    image = Image.open(path)
    emb = model.encode(image)
    embeddings.append(emb)

embeddings = np.array(embeddings)

print("Embedding Shape:", embeddings.shape)

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)
index.add(embeddings)

print("Total vectors in index:", index.ntotal)

def search_images(query, top_k=3):
    query_embedding = model.encode([query])

    distances, indices = index.search(
        np.array(query_embedding), top_k
    )

    return indices[0]

query = "dog"
results = search_images(query)

print("Results:", results)

plt.figure(figsize=(10,4))

for i, idx in enumerate(results):
    img = Image.open(image_paths[idx])

    plt.subplot(1,3,i+1)
    plt.imshow(img)
    plt.title(f"Result {i+1}")
    plt.axis("off")

plt.show()

def generate_explanation(query):
    explanation = f"The retrieved images match the query '{query}' because the visual features are similar."

    return explanation

print(generate_explanation(query))